name: Generate GitHub Contributions

on:
  workflow_run:
    workflows: ["Schedule"]
    types:
      - completed

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g github-contributions-generator

      - name: Generate GitHub Contributions SVG
        run: github-contributions-generator -u gauravrathod802 -o github-contribution-grid-snake.svg

      - name: Commit and push SVG
        run: |
          git config user.name "gauravrathod802"
          git config user.email "gauravrathod802@gmail.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update GitHub Contributions SVG"
          git push
