name: generate animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Generate GitHub Contributions SVG
        id: generate-svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: gauravrathod802
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Debug Output
        run: |
          ls -la dist/
          cat dist/github-contribution-grid-snake.svg
          cat dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          echo "Action outputs:"
          env | grep GITHUB_ACTIONS

      - name: Push SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
