name: GitHub Contributions Snake

on:
  workflow_run:
    workflows: ["Generate GitHub Contributions Snake"]
    types:
      - completed

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Generate GitHub Contributions SVG
        run: npm run generate

      - name: Push SVG to Output Branch
        run: npm run push

      - name: Complete job
        run: echo "Job complete"
