name: generate-animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Generate GitHub Contributions SVG
        uses: Platane/snk@master
        with:
          github_user_name: gauravrathod802
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push SVG to Output Branch
        run: |
          mkdir -p dist
          mv github-contribution-grid-snake.svg dist/
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add dist/
          git commit -m "Update GitHub Contributions SVG"
          git push origin output
