name: generate

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # Allows manual run of the job at any time
  workflow_dispatch:

  # Run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Download github-contributions-generator
        run: |
          curl -o github-contributions-generator.tar.gz -L https://github.com/Ashutosh00710/github-contributions-generator/tarball/main
          tar -xzf github-contributions-generator.tar.gz
          mv Ashutosh00710-github-contributions-generator-* github-contributions-generator
          cd github-contributions-generator
          npm install

      - name: Generate GitHub Contributions SVG
        run: |
          npx github-contributions-generator -u gauravrathod802 -c 20 -g '#1A1A1A' -o dist/github-contribution-grid-snake.svg

      - name: Push SVG to Output Branch
        run: |
          mkdir -p dist
          mv dist/github-contribution-grid-snake.svg dist/
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add dist/
          git commit -m "Update GitHub Contributions SVG"
          git push origin output
