name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"

workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gauravrathod802
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push changes
        run: |
          git config user.name "gauravrathod802"
          git config user.email "gauravrathod802@gmail.com"
          git add dist/
          git commit -m "Update GitHub Contributions"
          git push
